
 on:
  schedule:
    - cron:  '15 * * * *'
    
    
 jobs:
  ping:
   runs-on: ubuntu-latest
   steps:
   - name: Check the deployed service URL
     uses: jtalk/url-health-check-action@v2
     with:

      url: https://smallcrawler6.herokuapp.com/api/ping
      # Follow redirects, or just report success on 3xx status codes
      follow-redirect: false # Optional, defaults to "false"
      # Fail this action after this many failed attempts
      max-attempts: 3 
      # Delay between retries
      retry-delay: 15s 
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
     - run: echo 'The triggering workflow failed'
     - name: mailNotification
       uses: cinotify/github-action@main
       with:
        to: 'jordi_belda@hotmail.com'
        subject: 'Error BACKEND SMALL CRAWLER'
        body: 'Error in the ping of the backend of the small crawler. <br> url: https://smallcrawler6.herokuapp.com/api/ping '

       
  
